name: Daily Python Script Run

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to use Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v4  # Update to use Node.js 20
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: python AMC_API.py
    - name: execute py script
      run: |
        python AMC_API.py
        git config user.name EpiLogue09
        git config user.email gyou0907@gmail.com
        git add .
        git commit -m "cron generated"
        git push
