name: Daily Python Script Run

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 05:30 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: execute py script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python AMC_API.py --refresh-raw
        git config user.name EpiLogue09
        git config user.email gyou0907@gmail.com
        git add data/*.json showtime_*.json
        git commit -m "cron generated" || echo "No changes to commit"
        git push
